version: '3'

services:
  app:
    image: mesko56/to-up-app:v1
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - 'db_postgres'
      - 'db_mongo'
      - 'redis'

  db_postgres:
    image: postgres
    volumes:
      - './database/pg:/var/lib/postgresql/data'
    restart: always
    environment:
      POSTGRES_PASSWORD: meskosama
      POSTGRES_DB: to-up
    networks:
      - app-network

  db_mongo:
    image: mongo
    volumes:
      - './database/mongo:/data/db'
    networks:
      - app-network
    depends_on:
      - 'db_postgres'

  redis:
    image: redis:alpine
    volumes:
      - './database/redis:/data'
    networks:
      - app-network
    depends_on:
      - 'db_mongo'

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network
    volumes:
      - 'rabbitmq_data:/data'

networks:
  app-network:
    driver: bridge
volumes:
  rabbitmq_data:
